-- CREATE TABLE IF NOT EXISTS users (
--     id INT PRIMARY KEY AUTO_INCREMENT,
--     name VARCHAR(50) NOT NULL,
--     email VARCHAR(50) NOT NULL,
--     password VARCHAR(50) NOT NULL,
--     CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP
-- );

DROP TABLE users;